### PR TITLE
Controlling epochs as argument for XLMRMultiClass plugin

### PR DESCRIPTION
**Pull request by biswaroop1547**

### CODE REVIEW

**Comment by biswaroop1547** [comment]
this [pr](https://github.com/skit-ai/dialogy-template-simple-transformers/pull/101) takes care of template integration part.

**Comment by dakshvar22** [comment]
@biswaroop1547 Why can't we reuse `num_train_epochs` parameter from the config file? If you are not using the config file, you could still create the `args_map` variable containing `num_train_epochs` inside the `train` key and pass it to XLMR?
I'd like to avoid adding such one-off arguments to the constructor of a plugin.

**Comment by biswaroop1547** [comment]
@dakshvar22 agreed. Will make the update.

**Comment by biswaroop1547** [comment]
closing this pr as [this](https://github.com/skit-ai/dialogy-template-simple-transformers/pull/101/commits/57310834d73517f6e4ccdd0b6a7fde5359648b03) commit in template pr makes up for it.

**Pull request closed without merging**
